name: Oracle Cloud - Instance Creation Loop

on:
  schedule:
    - cron: '*/15 * * * *' # Corre automáticamente cada 15 minutos
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl, openssl

      - name: Install Dependencies
        run: composer install

      - name: Execute Instance Creation Script
        env:
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_PRIVATE: ${{ secrets.OCI_KEY_PRIVATE }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
        run: |
          # Script para ejecutar la herramienta PHP pasándole los secrets que guardaste
          php index.php
